In [136]:
import pandas as pd
import numpy as np

In [137]:
# tot_df = []
# for j,i in enumerate(np.arange(2002, 2021, 1)):
#     tot_df.append(pd.read_csv('../Data/Raw/CDC/'+ 
#                               str(i) +'.csv', sep = ',', skiprows = 4))
# df = pd.concat(tot_df, axis = 0)

In [138]:
df_1 = pd.read_csv("../Data/Raw/CDC/CDCSTDoverall2000-2020.csv",skiprows = 4)

In [139]:
df_1.head()

,Indicator,Year,Geography,FIPS,Cases,Rate per 100000
0,Primary and Secondary Syphilis,2020 (COVID-19 Pandemic),"Abbeville County, SC",45001,4,16.3
1,Primary and Secondary Syphilis,2019,"Abbeville County, SC",45001,3,12.2
2,Primary and Secondary Syphilis,2018,"Abbeville County, SC",45001,2,8.1
3,Primary and Secondary Syphilis,2017,"Abbeville County, SC",45001,1,4.1
4,Primary and Secondary Syphilis,2016,"Abbeville County, SC",45001,1,4.1

In [140]:
df_1.columns = df_1.columns.str.lower()
df_1.columns = df_1.columns.str.replace(' ','_')

In [141]:
df_1.loc[df_1["year"].str.startswith('2020',na=False), "year"] = "2020"

In [142]:
data_to_be_removed = ["cases","rate_per_100000"]

In [143]:
for col in data_to_be_removed:
    df_1.loc[df_1[col].str.contains("Data",na = False), col] = np.nan
    df_1[col] = df_1[col].str.replace(',','')
df_1[['cases','year','rate_per_100000']] = df_1[['cases','year','rate_per_100000']].apply(pd.to_numeric)

In [144]:
searchfor = ['Gonorrhea', 'Chlamydia']
df_1_refine = df_1[df_1.indicator.str.contains('|'.join(searchfor))]

In [146]:
df_1 = df_1_refine.pivot_table(index=['year','fips'], columns=['indicator']).reset_index()
# df.columns = df.columns.map('_'.join).str.strip('_')
df_1.head()

           year  fips     cases           rate_per_100000
indicator             Chlamydia Gonorrhea       Chlamydia Gonorrhea
0          2000  1001     139.0     107.0           316.3     243.4
1          2000  1003     221.0     139.0           156.3      98.3
2          2000  1005     152.0      79.0           523.4     272.0
3          2000  1007      53.0      29.0           266.6     145.9
4          2000  1009      31.0       2.0            60.6       3.9

In [153]:
df_1 = pd.read_csv("../Data/Intermediate/CDCSTDoverall2000_2020_processed.csv",index_col=0)

### Total Pop

In [155]:
df_pop = pd.read_csv("../Data/clean/nonACSDemographics/census_total_pop_2000_2010_clean.csv",index_col=0)

In [156]:
df_pop

        fips  year  total_pop
1       1001  2000      44021
2       1003  2000     141342
3       1005  2000      29015
4       1007  2000      19913
5       1009  2000      51107
...      ...   ...        ...
31935  56037  2009      44133
31936  56039  2009      21232
31937  56041  2009      21054
31938  56043  2009       8423
31939  56045  2009       7266

[31430 rows x 3 columns]

In [157]:
import glob
for f in glob.glob("../Data/clean/ACS/ACSDP05*"):
    df_pop = pd.concat([df_pop,pd.read_csv(f)[['fips','year','total_pop']]])

In [158]:
# df_pop_1 = df_pop.pivot_table(index=['fips'], columns=['year']).reset_index()

### 2020 Covariates

In [177]:
df_2_1 = pd.read_csv('../Data/clean/ACS/ACSDP032020_clean.csv',index_col=0)

In [178]:
df_2_1.head()

,per_capita_income_2020,employment_pop_ratio,unemployment_rate,pct_ind_agriculture_forestry_fishing_and_hunting_and_mining,pct_ind_construction,pct_ind_manufacturing,pct_ind_wholesale_trade,pct_ind_retail_trade,pct_ind_transportation_and_warehousing_and_utilities,pct_ind_information,...,pct_ind_educational_services_and_health_care_and_social_assistance,pct_ind_arts_entertainment_and_recreation_and_accommodation_and_food_services,pct_ind_other_services_except_public_administration,pct_ind_public_administration,health_insurance_rate,poverty_rate,id,geographic_area_name,year,fips
0,29804,55.4,2.9,0.8,7.5,11.1,3.2,10.7,5.7,1.1,...,20.4,8.4,5.0,10.7,92.0,15.2,0500000US01001,"Autauga County, Alabama",2020,1001
1,33751,55.8,3.9,1.8,8.0,9.7,2.7,13.6,5.1,1.1,...,19.3,9.9,5.0,5.3,90.5,9.2,0500000US01003,"Baldwin County, Alabama",2020,1003
2,20074,42.7,6.9,5.7,6.0,24.0,2.1,10.7,5.7,0.8,...,18.6,6.6,3.8,7.1,89.3,28.6,0500000US01005,"Barbour County, Alabama",2020,1005
3,22626,45.1,7.4,4.7,9.4,14.6,3.1,10.8,6.2,1.4,...,22.4,3.3,6.2,5.7,90.9,18.1,0500000US01007,"Bibb County, Alabama",2020,1007
4,25457,49.6,5.2,1.7,9.2,17.4,4.2,10.4,7.6,1.0,...,21.3,4.9,5.3,3.8,90.0,13.7,0500000US01009,"Blount County, Alabama",2020,1009

In [179]:
df_2_1 = df_2_1.drop(columns=['id','geographic_area_name'])

In [180]:
df_2_2 = pd.read_csv('../Data/clean/ACS/ACSDP052020_clean.csv',index_col = 0)

In [181]:
df_2_2.head()

,pct_sex_age_under_5,pct_sex_age_5_to_9,pct_sex_age_10_to_14,pct_sex_age_15_to_19,pct_sex_age_20_to_24,pct_sex_age_25_to_34,pct_sex_age_35_to_44,pct_sex_age_45_to_54,pct_sex_age_55_to_59,pct_sex_age_60_to_64,...,pct_one_or_more_race_native_american,pct_one_or_more_race_asian,pct_one_or_more_race_native_hawaiian_pacific_islander,pct_one_or_more_race_other_race,pct_ethnicity_hispanic,id,Geographic Area Name,year,total_pop,fips
0,5.8,6.7,6.6,6.7,6.2,12.7,13.1,14.0,7.4,5.5,...,0.8,1.9,0.0,1.3,2.9,0500000US01001,"Autauga County, Alabama",2020,55639,1001
1,5.5,5.3,6.9,6.0,5.1,11.2,12.1,13.1,7.0,7.4,...,1.5,1.4,0.3,2.3,4.6,0500000US01003,"Baldwin County, Alabama",2020,218289,1003
2,5.3,6.2,5.7,5.5,6.1,14.6,12.2,12.5,6.4,6.4,...,1.3,0.6,0.1,4.0,4.4,0500000US01005,"Barbour County, Alabama",2020,25026,1005
3,5.6,5.3,5.4,6.5,5.8,14.5,13.8,14.0,6.7,6.0,...,0.4,0.3,0.0,0.0,2.7,0500000US01007,"Bibb County, Alabama",2020,22374,1007
4,6.1,6.0,7.1,6.4,5.5,11.9,12.2,13.2,6.8,6.8,...,1.4,0.5,0.1,2.3,9.3,0500000US01009,"Blount County, Alabama",2020,57755,1009

In [182]:
df_2_2 = df_2_2.drop(columns=['id','Geographic Area Name','total_pop'])

### Final Merge

In [188]:
df_cov = pd.merge(df_2_2,df_2_1,on=['fips','year'])

In [189]:
df_cov

,pct_sex_age_under_5,pct_sex_age_5_to_9,pct_sex_age_10_to_14,pct_sex_age_15_to_19,pct_sex_age_20_to_24,pct_sex_age_25_to_34,pct_sex_age_35_to_44,pct_sex_age_45_to_54,pct_sex_age_55_to_59,pct_sex_age_60_to_64,...,pct_ind_transportation_and_warehousing_and_utilities,pct_ind_information,pct_ind_finance_and_insurance_and_real_estate_and_rental_and_leasing,pct_ind_professional_scientific_and_management_and_administrative_and_waste_management_services,pct_ind_educational_services_and_health_care_and_social_assistance,pct_ind_arts_entertainment_and_recreation_and_accommodation_and_food_services,pct_ind_other_services_except_public_administration,pct_ind_public_administration,health_insurance_rate,poverty_rate
0,5.8,6.7,6.6,6.7,6.2,12.7,13.1,14.0,7.4,5.5,...,5.7,1.1,5.5,9.8,20.4,8.4,5.0,10.7,92.0,15.2
1,5.5,5.3,6.9,6.0,5.1,11.2,12.1,13.1,7.0,7.4,...,5.1,1.1,7.6,10.7,19.3,9.9,5.0,5.3,90.5,9.2
2,5.3,6.2,5.7,5.5,6.1,14.6,12.2,12.5,6.4,6.4,...,5.7,0.8,3.9,5.1,18.6,6.6,3.8,7.1,89.3,28.6
3,5.6,5.3,5.4,6.5,5.8,14.5,13.8,14.0,6.7,6.0,...,6.2,1.4,5.0,7.0,22.4,3.3,6.2,5.7,90.9,18.1
4,6.1,6.0,7.1,6.4,5.5,11.9,12.2,13.2,6.8,6.8,...,7.6,1.0,6.0,7.5,21.3,4.9,5.3,3.8,90.0,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,4.3,5.0,5.9,6.5,6.7,12.7,12.2,13.1,6.5,6.9,...,3.9,1.1,3.6,9.5,23.6,10.0,6.2,7.1,90.4,45.7
3217,5.1,5.5,4.8,6.8,7.3,9.0,12.9,11.0,9.5,5.9,...,5.4,0.0,4.8,10.1,18.7,13.3,4.2,20.7,84.6,52.6
3218,4.8,5.8,5.9,7.4,7.4,12.3,11.1,13.1,7.7,6.8,...,2.9,0.5,2.5,8.1,23.9,5.6,4.4,12.7,96.5,46.4
3219,3.6,5.2,5.8,6.5,6.7,11.6,11.7,13.4,7.2,7.4,...,3.4,0.8,6.3,9.0,21.4,10.4,3.6,7.0,94.4,51.7
3220,3.8,5.0,5.9,6.0,6.1,11.3,11.9,13.4,8.1,6.3,...,3.6,0.6,4.1,6.0,27.1,7.8,4.3,13.6,94.1,48.9

In [190]:
df = pd.merge(df_1,df_pop,on=['fips','year'])

In [191]:
df

,year,fips,cases_chlamydia,cases_early_non-primary_non-secondary_syphilis,cases_gonorrhea,cases_primary_and_secondary_syphilis,rate_per_100000_chlamydia,rate_per_100000_early_non-primary_non-secondary_syphilis,rate_per_100000_gonorrhea,rate_per_100000_primary_and_secondary_syphilis,...,rate_per_100000_male_gonorrhea_native_hawaiian_other_pacific_islander,rate_per_100000_male_gonorrhea_white,rate_per_100000_male_primary_and_secondary_syphilis_american_indian_alaska_native,rate_per_100000_male_primary_and_secondary_syphilis_asian,rate_per_100000_male_primary_and_secondary_syphilis_black_african_american,rate_per_100000_male_primary_and_secondary_syphilis_hispanic_latino,rate_per_100000_male_primary_and_secondary_syphilis_multiracial,rate_per_100000_male_primary_and_secondary_syphilis_native_hawaiian_other_pacific_islander,rate_per_100000_male_primary_and_secondary_syphilis_white,total_pop
0,2000,45001,61.0,1.0,57.0,2.0,232.6,3.8,217.4,7.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26229
1,2000,22001,0.0,8.0,0.0,11.0,0.0,13.6,0.0,18.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58795
2,2000,51001,153.0,2.0,88.0,0.0,398.7,5.2,229.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38215
3,2000,16001,644.0,0.0,33.0,1.0,212.3,0.0,10.9,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303328
4,2000,19001,8.0,0.0,0.0,0.0,97.6,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8223
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66728,2020,4027,982.0,19.0,192.0,4.0,459.3,8.9,89.8,1.9,...,NaN,38.4,0.0,0.0,0.0,2.9,0.0,0.0,3.0,211931
66729,2020,8125,14.0,0.0,1.0,0.0,139.7,0.0,10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10013
66730,2020,48505,46.0,0.0,4.0,0.0,324.4,0.0,28.2,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,14243
66731,2020,48507,42.0,0.0,11.0,0.0,354.7,0.0,92.9,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11930
66732,2020,46137,17.0,0.0,12.0,0.0,616.8,0.0,435.4,0.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2767

In [195]:
df_final = pd.merge(df,df_cov,on =['year','fips'],how='left')

In [196]:
df_final

,year,fips,cases_chlamydia,cases_early_non-primary_non-secondary_syphilis,cases_gonorrhea,cases_primary_and_secondary_syphilis,rate_per_100000_chlamydia,rate_per_100000_early_non-primary_non-secondary_syphilis,rate_per_100000_gonorrhea,rate_per_100000_primary_and_secondary_syphilis,...,pct_ind_transportation_and_warehousing_and_utilities,pct_ind_information,pct_ind_finance_and_insurance_and_real_estate_and_rental_and_leasing,pct_ind_professional_scientific_and_management_and_administrative_and_waste_management_services,pct_ind_educational_services_and_health_care_and_social_assistance,pct_ind_arts_entertainment_and_recreation_and_accommodation_and_food_services,pct_ind_other_services_except_public_administration,pct_ind_public_administration,health_insurance_rate,poverty_rate
0,2000,45001,61.0,1.0,57.0,2.0,232.6,3.8,217.4,7.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,22001,0.0,8.0,0.0,11.0,0.0,13.6,0.0,18.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,51001,153.0,2.0,88.0,0.0,398.7,5.2,229.3,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,16001,644.0,0.0,33.0,1.0,212.3,0.0,10.9,0.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,19001,8.0,0.0,0.0,0.0,97.6,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66728,2020,4027,982.0,19.0,192.0,4.0,459.3,8.9,89.8,1.9,...,5.3,1.0,3.8,8.1,21.0,10.6,4.3,9.4,87.4,18.2
66729,2020,8125,14.0,0.0,1.0,0.0,139.7,0.0,10.0,0.0,...,9.3,1.0,3.0,8.6,16.1,9.5,3.2,4.0,88.1,11.4
66730,2020,48505,46.0,0.0,4.0,0.0,324.4,0.0,28.2,0.0,...,5.6,0.0,6.8,3.7,26.6,4.6,6.2,6.9,74.1,32.2
66731,2020,48507,42.0,0.0,11.0,0.0,354.7,0.0,92.9,0.0,...,5.9,2.3,0.5,2.3,38.0,8.4,4.9,3.2,83.8,35.2
66732,2020,46137,17.0,0.0,12.0,0.0,616.8,0.0,435.4,0.0,...,2.6,0.0,3.4,3.3,32.2,5.0,1.8,17.4,71.3,42.9

In [197]:
df_final.to_csv('../Data/Final/STI0220_cov20_pop0220.csv')