In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_excel(io = "../Data/Raw/nonACSDemographics/SAIPECountyPovertyAndIncome2009.xls", skiprows = 2, sheet_name="est09ALL")

df.head()

,State FIPS,County FIPS,Postal,Name,Poverty Estimate All Ages,90% CI Lower Bound,90% CI Upper Bound,Poverty Percent All Ages,90% CI Lower Bound.1,90% CI Upper Bound.1,...,90% CI Upper Bound.5,Median Household Income,90% CI Lower Bound.6,90% CI Upper Bound.6,Poverty Estimate Ages 0-4,90% CI Lower Bound.7,90% CI Upper Bound.7,Poverty Percent Ages 0-4,90% CI Lower Bound.8,90% CI Upper Bound.8
0,00,0.0,US,United States,42868163.0,42631574.0,43104752.0,14.3,14.3,14.4,...,18.4,50221.0,50147.0,50295.0,4849988.0,4792377.0,4907599.0,23.2,23.0,23.5
1,01,0.0,AL,Alabama,805223.0,789114.0,821333.0,17.5,17.2,17.9,...,23.6,40547.0,40037.0,41057.0,89398.0,84576.0,94221.0,28.7,27.2,30.3
2,01,1.0,AL,Autauga County,5653.0,4401.0,6905.0,11.2,8.7,13.7,...,18.0,53081.0,48727.0,57435.0,NaN,NaN,NaN,NaN,NaN,NaN
3,01,3.0,AL,Baldwin County,23590.0,20404.0,26776.0,13.3,11.5,15.1,...,21.4,48637.0,46195.0,51078.0,NaN,NaN,NaN,NaN,NaN,NaN
4,01,5.0,AL,Barbour County,8676.0,7407.0,9945.0,32.8,28.0,37.6,...,47.4,28802.0,26012.0,31591.0,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
list(df.columns)

['State FIPS',
 'County FIPS',
 'Postal',
 'Name',
 'Poverty Estimate All Ages',
 '90% CI Lower Bound',
 '90% CI Upper Bound',
 'Poverty Percent All Ages',
 '90% CI Lower Bound.1',
 '90% CI Upper Bound.1',
 'Poverty Estimate Under Age 18',
 '90% CI Lower Bound.2',
 '90% CI Upper Bound.2',
 'Poverty Percent Under Age 18',
 '90% CI Lower Bound.3',
 '90% CI Upper Bound.3',
 'Poverty Estimate Ages 5-17',
 '90% CI Lower Bound.4',
 '90% CI Upper Bound.4',
 'Poverty Percent Ages 5-17',
 '90% CI Lower Bound.5',
 '90% CI Upper Bound.5',
 'Median Household Income',
 '90% CI Lower Bound.6',
 '90% CI Upper Bound.6',
 'Poverty Estimate Ages 0-4',
 '90% CI Lower Bound.7',
 '90% CI Upper Bound.7',
 'Poverty Percent Ages 0-4',
 '90% CI Lower Bound.8',
 '90% CI Upper Bound.8']

In [63]:
df = df[["State FIPS", "County FIPS", "Name", "Poverty Percent All Ages", "Median Household Income"]]
df.head()

,State FIPS,County FIPS,Name,Poverty Percent All Ages,Median Household Income
0,00,0.0,United States,14.3,50221.0
1,01,0.0,Alabama,17.5,40547.0
2,01,1.0,Autauga County,11.2,53081.0
3,01,3.0,Baldwin County,13.3,48637.0
4,01,5.0,Barbour County,32.8,28802.0

In [64]:
df = df[df["County FIPS"] > 0]
df.head()

,State FIPS,County FIPS,Name,Poverty Percent All Ages,Median Household Income
2,01,1.0,Autauga County,11.2,53081.0
3,01,3.0,Baldwin County,13.3,48637.0
4,01,5.0,Barbour County,32.8,28802.0
5,01,7.0,Bibb County,18.1,38294.0
6,01,9.0,Blount County,14.6,41520.0

In [65]:
df["State FIPS"] = pd.to_numeric(df["State FIPS"])
df["fips"] = df["State FIPS"]*1000 + df["County FIPS"]
df = df.drop(columns = ["State FIPS", "County FIPS", "Name"])
df.head()

df.to_csv("../Data/Clean/nonACSDemographics/SAIPE2009_clean.csv")